# Generated by Django 4.2.4 on 2023-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hi! I am writing on varshneyblogs', null=True),
        ),
    ]
